config:
  validation: true
  warningsAsErrors: false
  excludes: ''

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']
style:
  UnusedImports:
    active: true
  MagicNumber:
    ignoreEnums: true
