name: Deploy API
on:
  push:
    branches:
      - 'test-and-update-github-action'
#    paths:
#      - '**/Version.kt'

jobs:
  build_and_deploy_api:
    name: Build and deploy API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout io page
        uses: actions/checkout@v3
        with:
          repository: Minirogue/minirogue.github.io
          token: ${{ secrets.MINROGUE_IO_TOKEN }}
      - name: Checkout HoloCanon
        uses: actions/checkout@v3
        with:
          path: holocanon
      - name: Generate the API data
        run: chmod +x holocanon/gradlew && holocanon/gradlew -p holocanon :api:run
      - name: Move api to io
        run:  rm -r holocanon-api && mv holocanon/api/holocanon-api holocanon-api
      - name: commit and push to the api repo
        run: git add holocanon-api && git push
